[tool.poetry]
name = "notsoerp"
version = "0.1.0"
description = ""
authors = ["vitalik.svt@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = '*'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
